#!/data/data/com.termux/files/usr/bin/bash

bin=/data/data/com.termux/files/usr/bin
file=/sdcard/termux-backup/termux-backup.tar.gz

green='\e[32m'
red='\e[31m'
off='\e[0m'

if ![[ -f bin/pv && -f bin/toilet ]]
then
	printf $green"Installing dependencies..."$off
	pkg update && pkg upgrade -y
	pkg install pv toilet
fi

clear

toilet -f slant -F metal -t "T-Backup"

sleep 2s

if [[ -d /sdcard/ ]]
then
	:
else
	termux-setup-storage
fi
if [[ -f $file ]]
then
	printf $red"\nA backup already exists in ${green}${file}\n"$off
	read -p $red"\nOverwrite it?([y]/n):"$off choice
	if [[ choice == 'y' || choice == '' ]]
	then
		:
	else
		printf $red"\nAborting...\n"$off
		sleep 2s
		exit
	fi
fi

printf $green"\nBackuping your data to \e[1m${file}\n"$off

if [[ -d /sdcard/termux-backup ]]
then
	:
else
	cd /sdcard && mkdir termux-backup
fi

cd /data/data/com.termux/files

tar -zcf - home usr | pv -pte > "$file"

printf $green"\nBackup done!\n"$off
