#!/data/data/com.termux/files/usr/bin/bash

bin=/data/data/com.termux/files/usr/bin

green='\e[32m'
off='\e[0m'

if [[ -f $bin/pv && -f $bin/toilet && -f $bin/figlet ]]
then
	printf $green"\nDependencies already installed\n"$off
else
	printf $green"\nInstalling dependencies...\n"$off
	pkg update
	pkg install pv toilet figlet
fi
sleep 1s
printf $green"\nAdding backup and restore to PATH...\n"$off

cp backup $bin/
cp restore $bin/

chmod +x $bin/backup
chmod +x $bin/restore

sleep 1s

printf $green"\nNow you can run backup and restore by just typing them\n\n"$off
