#!/data/data/com.termux/files/usr/bin/bash

file=/sdcard/termux-backup/termux-backup.tar.gz

green='\e[32m'
red='\e[31m'
off='\e[0m'

function term(){
	echo -e $red"Reverting back made changes..."$off
	cd /data/data/com.termux/files/
	if [[ -d home_backup ]]
	then
		rm -rf home
		rm -rf usr
		mv home_backup home
		mv usr_backup usr
		echo "Changes reverted."
		exit
	fi
	exit
}

trap term SIGINT

clear

toilet -f slant -F metal -t "T-Restore"

sleep 2s

if [[ -d /sdcard/ ]]
then
	:
else
	termux-setup-storage
fi
if [[ -f $file ]]
then
	printf $green"\nBackup file found in \e[1m${file}\n"$off
	sleep 2s
	printf $green"\nChecking file integrity...\n"$off
	if tar -tf "$file" &> /dev/null;then
		printf $green"\n\e[1mFile is good!\nProceeding...\n"$off
		sleep 1s
	else
		printf $red"File is courrupted.\n"
		printf "Aborting...\n"$off
		exit
	fi
else
	printf $red"\nNo backup found in \e[1m/sdcard/termux-backup/\n"$off
	printf $red"\nAborting...\n"$off
	exit
fi

printf $green"\nRestoring your data from \e[1m${file}\n${green}Note: After termux is restored restart the app.\n"$off

cd /data/data/com.termux/files

mv home home_backup
mv usr usr_backup

pv "$file" | tar -zxf - --preserve-permissions
